# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smcd2HL_sX3o2ZeEHaB3jvx2tBti_OW0
"""

# Función para calcular el descuento
def calcular_descuento(monto_total, porcentaje_descuento=10):
    return (porcentaje_descuento / 100) * monto_total

# Programa principal
monto1 = 100
descuento1 = calcular_descuento(monto1)
print(f"Descuento: ${descuento1}, Monto final: ${monto1 - descuento1}")

monto2 = 200
descuento2 = calcular_descuento(monto2, 15)
print(f"Descuento: ${descuento2}, Monto final: ${monto2 - descuento2}")