# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHi0HPIDTRYzOism02RCAlTtHmVLUSLN
"""

# Creación del diccionario "informacion_personal"
informacion_personal = {
    "nombre": "Santiago Tapuy",
    "edad": 21,
    "ciudad": "Puyo",
    "profesion": "Ing. agropecuario"
}

# Acceder y modificar el valor asociado con la clave "ciudad"
informacion_personal["ciudad"] = "Puyo"

# Agregar una nueva clave-valor para la profesión (ya existe, pero actualizamos por si acaso)
informacion_personal["profesion"] = "Zootecnista"

# Verificar si la clave "telefono" existe en el diccionario. Si no existe, agregarla
if "telefono" not in informacion_personal:
    informacion_personal["telefono"] = "0990529649"

# Eliminar la clave "edad" del diccionario
informacion_personal.pop("edad", None)

# Imprimir el diccionario final
print(informacion_personal)