# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5LbQYumlMKxYsXAKFJEFtlrZ0-VatwZ
"""

# Definir las dimensiones de la matriz 3D (ciudades x días de la semana x semanas)
ciudades = ["Ciudad1", "Ciudad2", "Ciudad3"]
dias_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]
semanas = 2  # Por simplicidad, consideramos 2 semanas

# Crear una matriz 3D para almacenar las temperaturas
# Por ejemplo: ciudad 1, día 1, semana 1 => 22 grados.
import random

# Inicializamos la matriz con temperaturas aleatorias entre 15 y 30 grados.
matriz_temperaturas = [[[random.randint(15, 30) for dia in dias_semana] for semana in range(semanas)] for ciudad in ciudades]

# Mostrar la matriz para verificar el contenido
for i, ciudad in enumerate(ciudades):
    print(f"Temperaturas para {ciudad}:")
    for j in range(semanas):
        print(f"Semana {j + 1}: {matriz_temperaturas[i][j]}")
    print()

# Calcular el promedio de temperaturas por ciudad y por semana
for i, ciudad in enumerate(ciudades):
    print(f"Promedio de temperaturas para {ciudad}:")
    for j in range(semanas):
        promedio_semana = sum(matriz_temperaturas[i][j]) / len(dias_semana)
        print(f"Semana {j + 1}: {promedio_semana:.2f}°C")
    print()